auto: true
permalink: /posts/:title
url: http://zpao.com
# lsi: true
exclude:
  - Rakefile
include:
  - .htaccess
  - .tumblr_htaccess

markdown: redcarpet
redcarpet:
  extensions: [smart, autolink, fenced_code_blocks, no_intra_emphasis, prettify]
