permalink: /posts/:title
url: https://zpao.com
# lsi: true
exclude:
  - Rakefile
  - Gemfile
  - Gemfile.lock
include:
  - .htaccess
  - .tumblr_htaccess

markdown: redcarpet
redcarpet:
  extensions:
    - smart
    - autolink
    - fenced_code_blocks
    - no_intra_emphasis
    - prettify
    - superscript
    - footnotes
    - strikethrough

sass:
  style: :expanded

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
